// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_protocol.proto

/*
Package server_msg is a generated protocol buffer package.

It is generated from these files:
	rpc_protocol.proto

It has these top-level messages:
	RegisterServiceRequest
	RegisterServiceResponse
	ServiceItem
	QueryServiceListResponse
	UpdateServiceListRequest
*/
package server_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google.golang.org/protobuf/types/known/emptypb"
import client_msg "sparrow/protocol/client_msg"
import client_msg2 "sparrow/protocol/client_msg"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enum_error_code from public import error_msg.proto
type EnumErrorCode client_msg.EnumErrorCode

var EnumErrorCode_name = client_msg.EnumErrorCode_name
var EnumErrorCode_value = client_msg.EnumErrorCode_value

func (x EnumErrorCode) String() string { return (client_msg.EnumErrorCode)(x).String() }

const EnumErrorCode_SUCCESS = EnumErrorCode(client_msg.EnumErrorCode_SUCCESS)
const EnumErrorCode_FAILD = EnumErrorCode(client_msg.EnumErrorCode_FAILD)

// ClientLoginReq from public import msg_login_server.proto
type ClientLoginReq client_msg2.ClientLoginReq

func (m *ClientLoginReq) Reset()              { (*client_msg2.ClientLoginReq)(m).Reset() }
func (m *ClientLoginReq) String() string      { return (*client_msg2.ClientLoginReq)(m).String() }
func (*ClientLoginReq) ProtoMessage()         {}
func (m *ClientLoginReq) GetAccounts() string { return (*client_msg2.ClientLoginReq)(m).GetAccounts() }
func (m *ClientLoginReq) GetPassword() string { return (*client_msg2.ClientLoginReq)(m).GetPassword() }

// ClientLoginRes from public import msg_login_server.proto
type ClientLoginRes client_msg2.ClientLoginRes

func (m *ClientLoginRes) Reset()         { (*client_msg2.ClientLoginRes)(m).Reset() }
func (m *ClientLoginRes) String() string { return (*client_msg2.ClientLoginRes)(m).String() }
func (*ClientLoginRes) ProtoMessage()    {}
func (m *ClientLoginRes) GetUid() uint64 { return (*client_msg2.ClientLoginRes)(m).GetUid() }

// ClientRegisterReq from public import msg_login_server.proto
type ClientRegisterReq client_msg2.ClientRegisterReq

func (m *ClientRegisterReq) Reset()         { (*client_msg2.ClientRegisterReq)(m).Reset() }
func (m *ClientRegisterReq) String() string { return (*client_msg2.ClientRegisterReq)(m).String() }
func (*ClientRegisterReq) ProtoMessage()    {}
func (m *ClientRegisterReq) GetAccounts() string {
	return (*client_msg2.ClientRegisterReq)(m).GetAccounts()
}
func (m *ClientRegisterReq) GetPassword() string {
	return (*client_msg2.ClientRegisterReq)(m).GetPassword()
}
func (m *ClientRegisterReq) GetChannel() int32 {
	return (*client_msg2.ClientRegisterReq)(m).GetChannel()
}

// ClientRegisterRes from public import msg_login_server.proto
type ClientRegisterRes client_msg2.ClientRegisterRes

func (m *ClientRegisterRes) Reset()         { (*client_msg2.ClientRegisterRes)(m).Reset() }
func (m *ClientRegisterRes) String() string { return (*client_msg2.ClientRegisterRes)(m).String() }
func (*ClientRegisterRes) ProtoMessage()    {}
func (m *ClientRegisterRes) GetUid() uint64 { return (*client_msg2.ClientRegisterRes)(m).GetUid() }

// QueryRoleListReq from public import msg_login_server.proto
type QueryRoleListReq client_msg2.QueryRoleListReq

func (m *QueryRoleListReq) Reset()         { (*client_msg2.QueryRoleListReq)(m).Reset() }
func (m *QueryRoleListReq) String() string { return (*client_msg2.QueryRoleListReq)(m).String() }
func (*QueryRoleListReq) ProtoMessage()    {}
func (m *QueryRoleListReq) GetUid() uint64 { return (*client_msg2.QueryRoleListReq)(m).GetUid() }

// QueryRoleListRes from public import msg_login_server.proto
type QueryRoleListRes client_msg2.QueryRoleListRes

func (m *QueryRoleListRes) Reset()         { (*client_msg2.QueryRoleListRes)(m).Reset() }
func (m *QueryRoleListRes) String() string { return (*client_msg2.QueryRoleListRes)(m).String() }
func (*QueryRoleListRes) ProtoMessage()    {}

// 注册服务
type RegisterServiceRequest struct {
	ServerType uint32 `protobuf:"varint,1,opt,name=server_type,json=serverType" json:"server_type,omitempty"`
	RpcPort    string `protobuf:"bytes,2,opt,name=rpc_port,json=rpcPort" json:"rpc_port,omitempty"`
}

func (m *RegisterServiceRequest) Reset()                    { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()               {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterServiceRequest) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *RegisterServiceRequest) GetRpcPort() string {
	if m != nil {
		return m.RpcPort
	}
	return ""
}

type RegisterServiceResponse struct {
	ErrorCode client_msg.EnumErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=client_msg.EnumErrorCode" json:"error_code,omitempty"`
	ServerId  uint32                   `protobuf:"varint,2,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
}

func (m *RegisterServiceResponse) Reset()                    { *m = RegisterServiceResponse{} }
func (m *RegisterServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterServiceResponse) ProtoMessage()               {}
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterServiceResponse) GetErrorCode() client_msg.EnumErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return client_msg.EnumErrorCode_SUCCESS
}

func (m *RegisterServiceResponse) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

// 请求服务列表
type ServiceItem struct {
	ServerId   uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerType uint32 `protobuf:"varint,2,opt,name=server_type,json=serverType" json:"server_type,omitempty"`
	Ip         string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
}

func (m *ServiceItem) Reset()                    { *m = ServiceItem{} }
func (m *ServiceItem) String() string            { return proto.CompactTextString(m) }
func (*ServiceItem) ProtoMessage()               {}
func (*ServiceItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceItem) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ServiceItem) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ServiceItem) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServiceItem) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type QueryServiceListResponse struct {
	ErrorCode  client_msg.EnumErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=client_msg.EnumErrorCode" json:"error_code,omitempty"`
	ServerList []*ServiceItem           `protobuf:"bytes,2,rep,name=server_list,json=serverList" json:"server_list,omitempty"`
}

func (m *QueryServiceListResponse) Reset()                    { *m = QueryServiceListResponse{} }
func (m *QueryServiceListResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryServiceListResponse) ProtoMessage()               {}
func (*QueryServiceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryServiceListResponse) GetErrorCode() client_msg.EnumErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return client_msg.EnumErrorCode_SUCCESS
}

func (m *QueryServiceListResponse) GetServerList() []*ServiceItem {
	if m != nil {
		return m.ServerList
	}
	return nil
}

// 更新服务列表
type UpdateServiceListRequest struct {
	ServerList []*ServiceItem `protobuf:"bytes,1,rep,name=server_list,json=serverList" json:"server_list,omitempty"`
}

func (m *UpdateServiceListRequest) Reset()                    { *m = UpdateServiceListRequest{} }
func (m *UpdateServiceListRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateServiceListRequest) ProtoMessage()               {}
func (*UpdateServiceListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateServiceListRequest) GetServerList() []*ServiceItem {
	if m != nil {
		return m.ServerList
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterServiceRequest)(nil), "server_msg.RegisterServiceRequest")
	proto.RegisterType((*RegisterServiceResponse)(nil), "server_msg.RegisterServiceResponse")
	proto.RegisterType((*ServiceItem)(nil), "server_msg.ServiceItem")
	proto.RegisterType((*QueryServiceListResponse)(nil), "server_msg.QueryServiceListResponse")
	proto.RegisterType((*UpdateServiceListRequest)(nil), "server_msg.UpdateServiceListRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RpcService service

type RpcServiceClient interface {
	// 服务注册
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// 服务请求
	QueryServiceList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*QueryServiceListResponse, error)
	// 服务更新
	UpdateServiceList(ctx context.Context, in *UpdateServiceListRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// 用户注册
	ClientRegister(ctx context.Context, in *client_msg2.ClientRegisterReq, opts ...grpc.CallOption) (*client_msg2.ClientRegisterRes, error)
	// 用户登录
	ClientLogin(ctx context.Context, in *client_msg2.ClientLoginReq, opts ...grpc.CallOption) (*client_msg2.ClientLoginRes, error)
	// 获取角色列表
	QueryRoleList(ctx context.Context, in *client_msg2.QueryRoleListReq, opts ...grpc.CallOption) (*client_msg2.QueryRoleListRes, error)
}

type rpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewRpcServiceClient(cc *grpc.ClientConn) RpcServiceClient {
	return &rpcServiceClient{cc}
}

func (c *rpcServiceClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	out := new(RegisterServiceResponse)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/RegisterService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) QueryServiceList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*QueryServiceListResponse, error) {
	out := new(QueryServiceListResponse)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/QueryServiceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) UpdateServiceList(ctx context.Context, in *UpdateServiceListRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/UpdateServiceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ClientRegister(ctx context.Context, in *client_msg2.ClientRegisterReq, opts ...grpc.CallOption) (*client_msg2.ClientRegisterRes, error) {
	out := new(client_msg2.ClientRegisterRes)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/ClientRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ClientLogin(ctx context.Context, in *client_msg2.ClientLoginReq, opts ...grpc.CallOption) (*client_msg2.ClientLoginRes, error) {
	out := new(client_msg2.ClientLoginRes)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/ClientLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) QueryRoleList(ctx context.Context, in *client_msg2.QueryRoleListReq, opts ...grpc.CallOption) (*client_msg2.QueryRoleListRes, error) {
	out := new(client_msg2.QueryRoleListRes)
	err := grpc.Invoke(ctx, "/server_msg.rpc_service/QueryRoleList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RpcService service

type RpcServiceServer interface {
	// 服务注册
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// 服务请求
	QueryServiceList(context.Context, *google_protobuf.Empty) (*QueryServiceListResponse, error)
	// 服务更新
	UpdateServiceList(context.Context, *UpdateServiceListRequest) (*google_protobuf.Empty, error)
	// 用户注册
	ClientRegister(context.Context, *client_msg2.ClientRegisterReq) (*client_msg2.ClientRegisterRes, error)
	// 用户登录
	ClientLogin(context.Context, *client_msg2.ClientLoginReq) (*client_msg2.ClientLoginRes, error)
	// 获取角色列表
	QueryRoleList(context.Context, *client_msg2.QueryRoleListReq) (*client_msg2.QueryRoleListRes, error)
}

func RegisterRpcServiceServer(s *grpc.Server, srv RpcServiceServer) {
	s.RegisterService(&_RpcService_serviceDesc, srv)
}

func _RpcService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_QueryServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).QueryServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/QueryServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).QueryServiceList(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_UpdateServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).UpdateServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/UpdateServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).UpdateServiceList(ctx, req.(*UpdateServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_ClientRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(client_msg2.ClientRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).ClientRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/ClientRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).ClientRegister(ctx, req.(*client_msg2.ClientRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_ClientLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(client_msg2.ClientLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).ClientLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/ClientLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).ClientLogin(ctx, req.(*client_msg2.ClientLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_QueryRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(client_msg2.QueryRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).QueryRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server_msg.rpc_service/QueryRoleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).QueryRoleList(ctx, req.(*client_msg2.QueryRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server_msg.rpc_service",
	HandlerType: (*RpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _RpcService_RegisterService_Handler,
		},
		{
			MethodName: "QueryServiceList",
			Handler:    _RpcService_QueryServiceList_Handler,
		},
		{
			MethodName: "UpdateServiceList",
			Handler:    _RpcService_UpdateServiceList_Handler,
		},
		{
			MethodName: "ClientRegister",
			Handler:    _RpcService_ClientRegister_Handler,
		},
		{
			MethodName: "ClientLogin",
			Handler:    _RpcService_ClientLogin_Handler,
		},
		{
			MethodName: "QueryRoleList",
			Handler:    _RpcService_QueryRoleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_protocol.proto",
}

func init() { proto.RegisterFile("rpc_protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x0a, 0x9a, 0xb1, 0x92, 0xc2, 0x1c, 0x52, 0xe3, 0x50, 0x51, 0x19, 0x0e, 0x39,
	0x39, 0x52, 0xb8, 0x20, 0x8e, 0x54, 0x3d, 0x54, 0x54, 0x28, 0x35, 0xe1, 0xd2, 0x8b, 0xd5, 0xda,
	0x83, 0xb5, 0x92, 0x9d, 0xdd, 0xee, 0x6e, 0x82, 0xf2, 0x17, 0x7c, 0x2b, 0x5f, 0x80, 0xbc, 0xeb,
	0x10, 0x3b, 0xc1, 0x11, 0x07, 0x6e, 0xab, 0x79, 0x2f, 0x6f, 0xde, 0x9b, 0x99, 0x18, 0x50, 0x8a,
	0x34, 0x11, 0x92, 0x6b, 0x9e, 0xf2, 0x22, 0x32, 0x0f, 0x04, 0x45, 0x72, 0x4d, 0x32, 0x29, 0x55,
	0x1e, 0x8c, 0x73, 0xce, 0xf3, 0x82, 0xa6, 0x06, 0x79, 0x5c, 0x7d, 0x9f, 0x52, 0x29, 0xf4, 0xc6,
	0x12, 0x83, 0x33, 0x92, 0x92, 0x1b, 0x5e, 0x5d, 0x18, 0x95, 0x2a, 0x4f, 0x0a, 0x9e, 0xb3, 0x65,
	0x62, 0x35, 0x6c, 0x3d, 0x5c, 0xc0, 0x28, 0xa6, 0x9c, 0x29, 0x4d, 0xf2, 0x2b, 0xc9, 0x35, 0x4b,
	0x29, 0xa6, 0xa7, 0x15, 0x29, 0x8d, 0x6f, 0xc0, 0xab, 0xbb, 0xe9, 0x8d, 0x20, 0xdf, 0xb9, 0x74,
	0x26, 0x83, 0xb8, 0x36, 0xb0, 0xd8, 0x08, 0xc2, 0x57, 0x70, 0x6a, 0x2c, 0x72, 0xa9, 0x7d, 0xf7,
	0xd2, 0x99, 0xf4, 0xe3, 0xe7, 0x52, 0xa4, 0x73, 0x2e, 0x75, 0x28, 0xe1, 0xfc, 0x40, 0x55, 0x09,
	0xbe, 0x54, 0x84, 0x1f, 0x01, 0xac, 0xb7, 0x94, 0x67, 0x56, 0x75, 0x38, 0x1b, 0x47, 0x69, 0xc1,
	0x68, 0xa9, 0x8d, 0x5f, 0x5a, 0xae, 0xca, 0x64, 0x47, 0x89, 0xfb, 0xe6, 0x7d, 0xc5, 0x33, 0xc2,
	0x31, 0xf4, 0x6b, 0x4b, 0x2c, 0x33, 0x2d, 0x07, 0xf1, 0xa9, 0x2d, 0xdc, 0x64, 0x21, 0x07, 0xaf,
	0xee, 0x75, 0xa3, 0xa9, 0x6c, 0x73, 0x9d, 0x36, 0x77, 0x3f, 0x9b, 0x7b, 0x90, 0x6d, 0x08, 0x2e,
	0x13, 0x7e, 0xcf, 0xa4, 0x72, 0x99, 0x40, 0x84, 0x13, 0x93, 0xf3, 0xc4, 0x54, 0xcc, 0x3b, 0xfc,
	0xe9, 0x80, 0x7f, 0xb7, 0x22, 0xb9, 0xa9, 0xdb, 0xde, 0x32, 0xa5, 0xff, 0x4b, 0xcc, 0x0f, 0x7f,
	0xdc, 0x15, 0x4c, 0x55, 0xb3, 0xed, 0x4d, 0xbc, 0xd9, 0x79, 0xb4, 0xdb, 0x7d, 0xd4, 0x08, 0xba,
	0xb5, 0x5d, 0x75, 0x0f, 0x17, 0xe0, 0x7f, 0x13, 0xd9, 0x83, 0xa6, 0x96, 0x25, 0xbb, 0xcf, 0x3d,
	0x55, 0xe7, 0x9f, 0x55, 0x67, 0xbf, 0x7a, 0xe0, 0x55, 0x9b, 0x56, 0x16, 0xc7, 0x7b, 0x38, 0xdb,
	0xdb, 0x2e, 0x86, 0x4d, 0x9d, 0xbf, 0x1f, 0x54, 0xf0, 0xf6, 0x28, 0xa7, 0x9e, 0xdb, 0x1c, 0x5e,
	0xec, 0xcf, 0x14, 0x47, 0x91, 0x3d, 0xf5, 0x68, 0x7b, 0xea, 0xd1, 0x75, 0x75, 0xea, 0xc1, 0xbb,
	0xa6, 0x60, 0xe7, 0x26, 0xee, 0xe0, 0xe5, 0xc1, 0x4c, 0xb0, 0xf5, 0xd3, 0xae, 0x91, 0x05, 0x1d,
	0x8d, 0xf1, 0x0b, 0x0c, 0xaf, 0xcc, 0x26, 0xb7, 0x29, 0xf0, 0xa2, 0xb9, 0xda, 0x36, 0x16, 0xd3,
	0x53, 0x70, 0x14, 0x56, 0x78, 0x0d, 0x9e, 0x2d, 0xde, 0x56, 0x7f, 0x50, 0x0c, 0x0e, 0xd9, 0x06,
	0xa8, 0x94, 0xba, 0x31, 0x85, 0x9f, 0x61, 0x60, 0xa6, 0x10, 0xf3, 0xc2, 0xa6, 0x7c, 0xdd, 0x24,
	0xb7, 0xa0, 0x4a, 0xea, 0x18, 0xaa, 0x3e, 0x5d, 0xdc, 0x8f, 0x95, 0x78, 0x90, 0x92, 0xff, 0x98,
	0x6e, 0x3f, 0x42, 0xd3, 0xdd, 0xcc, 0xe6, 0xce, 0xdc, 0x7d, 0x7c, 0x66, 0x80, 0xf7, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xe4, 0xbb, 0x55, 0xf2, 0xaa, 0x04, 0x00, 0x00,
}
