//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameServer.proto
namespace GameServer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginItem")]
  public partial class LoginItem : global::ProtoBuf.IExtensible
  {
    public LoginItem() {}
    
    private int _GroupNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"GroupNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GroupNum
    {
      get { return _GroupNum; }
      set { _GroupNum = value; }
    }
    private long _UserID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginItemResult")]
  public partial class LoginItemResult : global::ProtoBuf.IExtensible
  {
    public LoginItemResult() {}
    
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameServerMsg")]
    public enum GameServerMsg
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAMESERVER_UNKNOWN", Value=0)]
      GAMESERVER_UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_M_ECHO_PACKET", Value=1001)]
      CTS_M_ECHO_PACKET = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_ECHO_PACKET_MOBILE", Value=0)]
      CTS_S_ECHO_PACKET_MOBILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_ECHO_PACKET_PC", Value=1)]
      CTS_S_ECHO_PACKET_PC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_M_LOGIN", Value=1002)]
      CTS_M_LOGIN = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_MOBILE_LOGIN", Value=0)]
      CTS_S_MOBILE_LOGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_PC_LOGIN", Value=1)]
      CTS_S_PC_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_M_ECHO_PACKET_RESULT", Value=11001)]
      STC_M_ECHO_PACKET_RESULT = 11001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_ECHO_PACKET_MOBILE_RESULT", Value=0)]
      STC_S_ECHO_PACKET_MOBILE_RESULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_ECHO_PACKET_PC_RESULT", Value=1)]
      STC_S_ECHO_PACKET_PC_RESULT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_M_LOGIN_RESULT", Value=11002)]
      STC_M_LOGIN_RESULT = 11002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_MOBILE_LOGIN_RESULT", Value=0)]
      STC_S_MOBILE_LOGIN_RESULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_PC_LOGIN_RESULT", Value=1)]
      STC_S_PC_LOGIN_RESULT = 1
    }
  
}