//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginServer.proto
namespace LoginServer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginItem")]
  public partial class LoginItem : global::ProtoBuf.IExtensible
  {
    public LoginItem() {}
    
    private string _AccountsName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountsName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountsName
    {
      get { return _AccountsName; }
      set { _AccountsName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private byte[] _nickname = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginItemResult")]
  public partial class LoginItemResult : global::ProtoBuf.IExtensible
  {
    public LoginItemResult() {}
    
    private int _errorcode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private long _userid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginServerMsg")]
    public enum LoginServerMsg
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGINSERVER_UNKNOWN", Value=0)]
      LOGINSERVER_UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_M_ECHO_PACKET", Value=1001)]
      CTS_M_ECHO_PACKET = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_ECHO_PACKET_MOBILE", Value=0)]
      CTS_S_ECHO_PACKET_MOBILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_ECHO_PACKET_PC", Value=1)]
      CTS_S_ECHO_PACKET_PC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_M_LOGIN", Value=1002)]
      CTS_M_LOGIN = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_MOBILE_LOGIN", Value=0)]
      CTS_S_MOBILE_LOGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_S_PC_LOGIN", Value=1)]
      CTS_S_PC_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_M_ECHO_PACKET_RESULT", Value=11001)]
      STC_M_ECHO_PACKET_RESULT = 11001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_ECHO_PACKET_MOBILE_RESULT", Value=0)]
      STC_S_ECHO_PACKET_MOBILE_RESULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_ECHO_PACKET_PC_RESULT", Value=1)]
      STC_S_ECHO_PACKET_PC_RESULT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_M_LOGIN_RESULT", Value=11002)]
      STC_M_LOGIN_RESULT = 11002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_MOBILE_LOGIN_RESULT", Value=0)]
      STC_S_MOBILE_LOGIN_RESULT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_S_PC_LOGIN_RESULT", Value=1)]
      STC_S_PC_LOGIN_RESULT = 1
    }
  
}