//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
namespace msg
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageID")]
    public enum MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BEGIN", Value=0)]
      MSG_BEGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_NORMAL_MSGID_BEGIN", Value=100000)]
      MSG_NORMAL_MSGID_BEGIN = 100000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHECK_VERSION_REQ", Value=100001)]
      MSG_CHECK_VERSION_REQ = 100001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHECK_VERSION_ACK", Value=100002)]
      MSG_CHECK_VERSION_ACK = 100002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_REG_REQ", Value=100003)]
      MSG_ACCOUNT_REG_REQ = 100003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_REG_ACK", Value=100004)]
      MSG_ACCOUNT_REG_ACK = 100004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_LOGIN_REQ", Value=100005)]
      MSG_ACCOUNT_LOGIN_REQ = 100005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACCOUNT_LOGIN_ACK", Value=100006)]
      MSG_ACCOUNT_LOGIN_ACK = 100006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DB_EXE_SQL_REQ", Value=100007)]
      MSG_DB_EXE_SQL_REQ = 100007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DB_EXE_SQL_ACK", Value=100008)]
      MSG_DB_EXE_SQL_ACK = 100008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SERVER_LIST_REQ", Value=100009)]
      MSG_SERVER_LIST_REQ = 100009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SERVER_LIST_ACK", Value=100010)]
      MSG_SERVER_LIST_ACK = 100010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SELECT_SERVER_REQ", Value=100011)]
      MSG_SELECT_SERVER_REQ = 100011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SELECT_SERVER_ACK", Value=100012)]
      MSG_SELECT_SERVER_ACK = 100012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_LOGIN_REQ", Value=100013)]
      MSG_LOGIC_REGTO_LOGIN_REQ = 100013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_LOGIN_ACK", Value=100014)]
      MSG_LOGIC_REGTO_LOGIN_ACK = 100014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_UPDATE_REQ", Value=100015)]
      MSG_LOGIC_UPDATE_REQ = 100015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_UPDATE_ACK", Value=100016)]
      MSG_LOGIC_UPDATE_ACK = 100016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GAME_REGTO_LOGIC_REQ", Value=100017)]
      MSG_GAME_REGTO_LOGIC_REQ = 100017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GAME_REGTO_LOGIC_ACK", Value=100018)]
      MSG_GAME_REGTO_LOGIC_ACK = 100018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_CENTER_REQ", Value=100019)]
      MSG_LOGIC_REGTO_CENTER_REQ = 100019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIC_REGTO_CENTER_ACK", Value=100020)]
      MSG_LOGIC_REGTO_CENTER_ACK = 100020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOG_DATA_NTF", Value=100021)]
      MSG_LOG_DATA_NTF = 100021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PHP_GM_COMMAND_REQ", Value=100022)]
      MSG_PHP_GM_COMMAND_REQ = 100022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PHP_GM_COMMAND_ACK", Value=100023)]
      MSG_PHP_GM_COMMAND_ACK = 100023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_WATCH_HEART_BEAT_REQ", Value=100024)]
      MSG_WATCH_HEART_BEAT_REQ = 100024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_WATCH_HEART_BEAT_ACK", Value=100025)]
      MSG_WATCH_HEART_BEAT_ACK = 100025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_REMOVE_CONNECT_NTY", Value=100026)]
      MSG_REMOVE_CONNECT_NTY = 100026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DISCONNECT_NTY", Value=100032)]
      MSG_DISCONNECT_NTY = 100032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_DATA_CHANGE_NTY", Value=100033)]
      MSG_ROLE_DATA_CHANGE_NTY = 100033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SET_LAST_SERVER_NTY", Value=100034)]
      MSG_SET_LAST_SERVER_NTY = 100034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GM_SHUTDOWN_SVR_REQ", Value=100035)]
      MSG_GM_SHUTDOWN_SVR_REQ = 100035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GM_SHUTDOWN_SVR_ACK", Value=100036)]
      MSG_GM_SHUTDOWN_SVR_ACK = 100036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UDP_CONNECT_REQ", Value=100037)]
      MSG_UDP_CONNECT_REQ = 100037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UDP_CONNECT_ACK", Value=100038)]
      MSG_UDP_CONNECT_ACK = 100038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SEAL_ACCOUNT_REQ", Value=100039)]
      MSG_SEAL_ACCOUNT_REQ = 100039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SEAL_ACCOUNT_ACK", Value=100040)]
      MSG_SEAL_ACCOUNT_ACK = 100040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DB_WRITE_ERROR_NTY", Value=100041)]
      MSG_DB_WRITE_ERROR_NTY = 100041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_NORMAL_MSGID_END", Value=199999)]
      MSG_NORMAL_MSGID_END = 199999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGICSVR_MSGID_BEGIN", Value=200000)]
      MSG_LOGICSVR_MSGID_BEGIN = 200000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LIST_REQ", Value=200001)]
      MSG_ROLE_LIST_REQ = 200001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LIST_ACK", Value=200002)]
      MSG_ROLE_LIST_ACK = 200002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_CREATE_REQ", Value=200003)]
      MSG_ROLE_CREATE_REQ = 200003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_CREATE_ACK", Value=200004)]
      MSG_ROLE_CREATE_ACK = 200004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_DELETE_REQ", Value=200005)]
      MSG_ROLE_DELETE_REQ = 200005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_DELETE_ACK", Value=200006)]
      MSG_ROLE_DELETE_ACK = 200006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGIN_REQ", Value=200007)]
      MSG_ROLE_LOGIN_REQ = 200007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGIN_ACK", Value=200008)]
      MSG_ROLE_LOGIN_ACK = 200008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGOUT_REQ", Value=200009)]
      MSG_ROLE_LOGOUT_REQ = 200009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_LOGOUT_ACK", Value=200010)]
      MSG_ROLE_LOGOUT_ACK = 200010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_NOTIFY_INTO_SCENE", Value=200014)]
      MSG_NOTIFY_INTO_SCENE = 200014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COPYINFO_REPORT_REQ", Value=200016)]
      MSG_COPYINFO_REPORT_REQ = 200016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MAIN_COPY_REQ", Value=200017)]
      MSG_MAIN_COPY_REQ = 200017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MAIN_COPY_ACK", Value=200018)]
      MSG_MAIN_COPY_ACK = 200018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ABORT_SCENE_NTF", Value=200019)]
      MSG_ABORT_SCENE_NTF = 200019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CLIENT_LOG_REQ", Value=200020)]
      MSG_CLIENT_LOG_REQ = 200020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BACK_TO_CITY_REQ", Value=200021)]
      MSG_BACK_TO_CITY_REQ = 200021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BACK_TO_CITY_ACK", Value=200022)]
      MSG_BACK_TO_CITY_ACK = 200022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BATTLE_RESULT_NTY", Value=200023)]
      MSG_BATTLE_RESULT_NTY = 200023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MAINCOPY_RESULT_NTY", Value=200024)]
      MSG_MAINCOPY_RESULT_NTY = 200024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_CHANG_NTY", Value=200025)]
      MSG_ROLE_CHANG_NTY = 200025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BAG_CHANGE_NTY", Value=200026)]
      MSG_BAG_CHANGE_NTY = 200026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PET_CHANGE_NTY", Value=200027)]
      MSG_PET_CHANGE_NTY = 200027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_EQUIP_CHANGE_NTY", Value=200028)]
      MSG_EQUIP_CHANGE_NTY = 200028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PARTNER_CHANGE_NTY", Value=200029)]
      MSG_PARTNER_CHANGE_NTY = 200029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MOUNT_CHANGE_NTY", Value=200030)]
      MSG_MOUNT_CHANGE_NTY = 200030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_OTHER_LOGIN_NTY", Value=200031)]
      MSG_ROLE_OTHER_LOGIN_NTY = 200031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_MESSAGE_REQ", Value=200032)]
      MSG_CHAT_MESSAGE_REQ = 200032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_MESSAGE_ACK", Value=200033)]
      MSG_CHAT_MESSAGE_ACK = 200033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_MESSAGE_NTY", Value=200034)]
      MSG_CHAT_MESSAGE_NTY = 200034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_EQUIP_REQ", Value=200035)]
      MSG_SETUP_EQUIP_REQ = 200035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_EQUIP_ACK", Value=200036)]
      MSG_SETUP_EQUIP_ACK = 200036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_EQUIP_REQ", Value=200037)]
      MSG_UNSET_EQUIP_REQ = 200037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_EQUIP_ACK", Value=200038)]
      MSG_UNSET_EQUIP_ACK = 200038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_PET_REQ", Value=200039)]
      MSG_SETUP_PET_REQ = 200039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_PET_ACK", Value=200040)]
      MSG_SETUP_PET_ACK = 200040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_PET_REQ", Value=200041)]
      MSG_UNSET_PET_REQ = 200041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_PET_ACK", Value=200042)]
      MSG_UNSET_PET_ACK = 200042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_PARTNER_REQ", Value=200043)]
      MSG_SETUP_PARTNER_REQ = 200043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_PARTNER_ACK", Value=200044)]
      MSG_SETUP_PARTNER_ACK = 200044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_PARTNER_REQ", Value=200045)]
      MSG_UNSET_PARTNER_REQ = 200045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_PARTNER_ACK", Value=200046)]
      MSG_UNSET_PARTNER_ACK = 200046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_MOUNT_REQ", Value=200047)]
      MSG_SETUP_MOUNT_REQ = 200047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_MOUNT_ACK", Value=200048)]
      MSG_SETUP_MOUNT_ACK = 200048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_MOUNT_REQ", Value=200049)]
      MSG_UNSET_MOUNT_REQ = 200049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_MOUNT_ACK", Value=200050)]
      MSG_UNSET_MOUNT_ACK = 200050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_ITEM_REQ", Value=200051)]
      MSG_USE_ITEM_REQ = 200051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_ITEM_ACK", Value=200052)]
      MSG_USE_ITEM_ACK = 200052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_GEM_REQ", Value=200053)]
      MSG_SETUP_GEM_REQ = 200053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SETUP_GEM_ACK", Value=200054)]
      MSG_SETUP_GEM_ACK = 200054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_GEM_REQ", Value=200055)]
      MSG_UNSET_GEM_REQ = 200055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_UNSET_GEM_ACK", Value=200056)]
      MSG_UNSET_GEM_ACK = 200056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_RECONNECT_REQ", Value=200057)]
      MSG_ROLE_RECONNECT_REQ = 200057,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_RECONNECT_ACK", Value=200058)]
      MSG_ROLE_RECONNECT_ACK = 200058,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MAIL_CHANGE_NTY", Value=200059)]
      MSG_MAIL_CHANGE_NTY = 200059,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TASK_CHANGE_NTY", Value=200060)]
      MSG_TASK_CHANGE_NTY = 200060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BROAD_MESSAGE_NOTIFY", Value=200061)]
      MSG_BROAD_MESSAGE_NOTIFY = 200061,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GASVR_REGTO_PROXY_REQ", Value=200062)]
      MSG_GASVR_REGTO_PROXY_REQ = 200062,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GASVR_REGTO_PROXY_ACK", Value=200063)]
      MSG_GASVR_REGTO_PROXY_ACK = 200063,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_BUY_REQ", Value=200064)]
      MSG_STORE_BUY_REQ = 200064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_BUY_ACK", Value=200065)]
      MSG_STORE_BUY_ACK = 200065,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GEM_CHANGE_NTY", Value=200066)]
      MSG_GEM_CHANGE_NTY = 200066,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_RANDOM_NAME_REQ", Value=200067)]
      MSG_RANDOM_NAME_REQ = 200067,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_RANDOM_NAME_ACK", Value=200068)]
      MSG_RANDOM_NAME_ACK = 200068,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_REBORN_REQ", Value=200069)]
      MSG_ROLE_REBORN_REQ = 200069,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ROLE_REBORN_ACK", Value=200070)]
      MSG_ROLE_REBORN_ACK = 200070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_ROOM_REQ", Value=200071)]
      MSG_CREATE_ROOM_REQ = 200071,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_ROOM_ACK", Value=200072)]
      MSG_CREATE_ROOM_ACK = 200072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_JOIN_ROOM_REQ", Value=200073)]
      MSG_JOIN_ROOM_REQ = 200073,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_JOIN_ROOM_ACK", Value=200074)]
      MSG_JOIN_ROOM_ACK = 200074,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_KICK_ROOM_REQ", Value=200075)]
      MSG_KICK_ROOM_REQ = 200075,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_KICK_ROOM_ACK", Value=200076)]
      MSG_KICK_ROOM_ACK = 200076,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_ROOM_REQ", Value=200077)]
      MSG_LEAVE_ROOM_REQ = 200077,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_ROOM_ACK", Value=200078)]
      MSG_LEAVE_ROOM_ACK = 200078,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_START_ROOM_REQ", Value=200079)]
      MSG_START_ROOM_REQ = 200079,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_START_ROOM_ACK", Value=200080)]
      MSG_START_ROOM_ACK = 200080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BROAD_ROOM_NOTIFY", Value=200081)]
      MSG_BROAD_ROOM_NOTIFY = 200081,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TEST_ADD_ITEM", Value=299998)]
      MSG_TEST_ADD_ITEM = 299998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGICSVR_MSGID_END", Value=299999)]
      MSG_LOGICSVR_MSGID_END = 299999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SCENESVR_MSGID_BEGIN", Value=300000)]
      MSG_SCENESVR_MSGID_BEGIN = 300000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_SCENE_REQ", Value=300001)]
      MSG_CREATE_SCENE_REQ = 300001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_SCENE_ACK", Value=300002)]
      MSG_CREATE_SCENE_ACK = 300002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DELETE_SCENE_REQ", Value=300003)]
      MSG_DELETE_SCENE_REQ = 300003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DELETE_SCENE_ACK", Value=300004)]
      MSG_DELETE_SCENE_ACK = 300004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SCENE_DESTROY_REQ", Value=300005)]
      MSG_SCENE_DESTROY_REQ = 300005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SCENE_DESTROY_ACK", Value=300006)]
      MSG_SCENE_DESTROY_ACK = 300006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TRANSFER_DATA_REQ", Value=300007)]
      MSG_TRANSFER_DATA_REQ = 300007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TRANSFER_DATA_ACK", Value=300008)]
      MSG_TRANSFER_DATA_ACK = 300008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_NOTIFY_ROLE_ENTER_REQ", Value=300009)]
      MSG_NOTIFY_ROLE_ENTER_REQ = 300009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_NOTIFY_ROLE_ENTER_ACK", Value=300010)]
      MSG_NOTIFY_ROLE_ENTER_ACK = 300010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_SCENE_REQ", Value=300011)]
      MSG_ENTER_SCENE_REQ = 300011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ENTER_SCENE_ACK", Value=300012)]
      MSG_ENTER_SCENE_ACK = 300012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_SCENE_REQ", Value=300013)]
      MSG_LEAVE_SCENE_REQ = 300013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LEAVE_SCENE_ACK", Value=300014)]
      MSG_LEAVE_SCENE_ACK = 300014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ABORT_SCENE_REQ", Value=300015)]
      MSG_ABORT_SCENE_REQ = 300015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ABORT_SCENE_ACK", Value=300016)]
      MSG_ABORT_SCENE_ACK = 300016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKILL_CAST_REQ", Value=300017)]
      MSG_SKILL_CAST_REQ = 300017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKILL_CAST_ACK", Value=300018)]
      MSG_SKILL_CAST_ACK = 300018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKILL_CAST_NTF", Value=300019)]
      MSG_SKILL_CAST_NTF = 300019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKILL_RESULT_NTF", Value=300020)]
      MSG_SKILL_RESULT_NTF = 300020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_NEW_NTF", Value=300021)]
      MSG_OBJECT_NEW_NTF = 300021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_CHANGE_NTF", Value=300022)]
      MSG_OBJECT_CHANGE_NTF = 300022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_REMOVE_NTF", Value=300023)]
      MSG_OBJECT_REMOVE_NTF = 300023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_ACTION_REQ", Value=300024)]
      MSG_OBJECT_ACTION_REQ = 300024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_ACTION_ACK", Value=300025)]
      MSG_OBJECT_ACTION_ACK = 300025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_HEART_BEAT_REQ", Value=300026)]
      MSG_HEART_BEAT_REQ = 300026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_HEART_BEAT_ACK", Value=300027)]
      MSG_HEART_BEAT_ACK = 300027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_HP_BOOTTLE_REQ", Value=300028)]
      MSG_USE_HP_BOOTTLE_REQ = 300028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_HP_BOOTTLE_ACK", Value=300029)]
      MSG_USE_HP_BOOTTLE_ACK = 300029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_MP_BOOTTLE_REQ", Value=300030)]
      MSG_USE_MP_BOOTTLE_REQ = 300030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_USE_MP_BOOTTLE_ACK", Value=300031)]
      MSG_USE_MP_BOOTTLE_ACK = 300031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OBJECT_DIE_NOTIFY", Value=300032)]
      MSG_OBJECT_DIE_NOTIFY = 300032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BATTLE_CHAT_REQ", Value=300033)]
      MSG_BATTLE_CHAT_REQ = 300033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BATTLE_CHAT_ACK", Value=300034)]
      MSG_BATTLE_CHAT_ACK = 300034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BULLET_NEW_NTF", Value=300035)]
      MSG_BULLET_NEW_NTF = 300035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SWITCH_MOUNT_REQ", Value=300036)]
      MSG_SWITCH_MOUNT_REQ = 300036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SWITCH_MOUNT_ACK", Value=300037)]
      MSG_SWITCH_MOUNT_ACK = 300037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PLAYER_CHAGE_NTF", Value=300038)]
      MSG_PLAYER_CHAGE_NTF = 300038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_ACTOR_HITEFFECT_NTF", Value=300039)]
      MSG_ACTOR_HITEFFECT_NTF = 300039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MOUNT_RIDING_REQ", Value=300040)]
      MSG_MOUNT_RIDING_REQ = 300040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_MOUNT_RIDING_ACK", Value=300041)]
      MSG_MOUNT_RIDING_ACK = 300041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SCENESVR_MSGID_END", Value=399999)]
      MSG_SCENESVR_MSGID_END = 399999
    }
  
}