// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_server.proto

/*
Package msg_server is a generated protocol buffer package.

It is generated from these files:
	msg_server.proto

It has these top-level messages:
	RegisterServiceRequest
	RegisterServiceResponse
	ServiceItem
	QueryServiceListResponse
	UpdateServiceListRequest
*/
package msg_server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google.golang.org/protobuf/types/known/emptypb"
import error_code "sparrow/protocol/error_code"
import msg_client "sparrow/protocol/msg_client"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enum_error_code from public import error_code.proto
type EnumErrorCode error_code.EnumErrorCode

var EnumErrorCode_name = error_code.EnumErrorCode_name
var EnumErrorCode_value = error_code.EnumErrorCode_value

func (x EnumErrorCode) String() string { return (error_code.EnumErrorCode)(x).String() }

const EnumErrorCode_SUCCESS = EnumErrorCode(error_code.EnumErrorCode_SUCCESS)
const EnumErrorCode_FAILD = EnumErrorCode(error_code.EnumErrorCode_FAILD)
const EnumErrorCode_LOGIN_ACCOUNTS_NOT_EXISTS = EnumErrorCode(error_code.EnumErrorCode_LOGIN_ACCOUNTS_NOT_EXISTS)
const EnumErrorCode_LOGIN_PASSWORD_ERROR = EnumErrorCode(error_code.EnumErrorCode_LOGIN_PASSWORD_ERROR)
const EnumErrorCode_REGISTER_ACCOUNTS_EXISTS = EnumErrorCode(error_code.EnumErrorCode_REGISTER_ACCOUNTS_EXISTS)
const EnumErrorCode_REGISTER_ACCOUNTS_FORMAT_ERROR = EnumErrorCode(error_code.EnumErrorCode_REGISTER_ACCOUNTS_FORMAT_ERROR)
const EnumErrorCode_REGISTER_PASSWORD_FORMAT_ERROR = EnumErrorCode(error_code.EnumErrorCode_REGISTER_PASSWORD_FORMAT_ERROR)
const EnumErrorCode_ROLE_LIST_EMPTY = EnumErrorCode(error_code.EnumErrorCode_ROLE_LIST_EMPTY)
const EnumErrorCode_ROLE_LIST_ERROR = EnumErrorCode(error_code.EnumErrorCode_ROLE_LIST_ERROR)
const EnumErrorCode_ROLE_NAME_EXISTS = EnumErrorCode(error_code.EnumErrorCode_ROLE_NAME_EXISTS)
const EnumErrorCode_ROLE_NAME_FORMAT_ERROR = EnumErrorCode(error_code.EnumErrorCode_ROLE_NAME_FORMAT_ERROR)
const EnumErrorCode_ROLE_LIST_ACCOUNT_NOT_EXISTS = EnumErrorCode(error_code.EnumErrorCode_ROLE_LIST_ACCOUNT_NOT_EXISTS)

// ClientLoginReq from public import msg_client.proto
type ClientLoginReq msg_client.ClientLoginReq

func (m *ClientLoginReq) Reset()              { (*msg_client.ClientLoginReq)(m).Reset() }
func (m *ClientLoginReq) String() string      { return (*msg_client.ClientLoginReq)(m).String() }
func (*ClientLoginReq) ProtoMessage()         {}
func (m *ClientLoginReq) GetAccounts() string { return (*msg_client.ClientLoginReq)(m).GetAccounts() }
func (m *ClientLoginReq) GetPassword() string { return (*msg_client.ClientLoginReq)(m).GetPassword() }

// ClientLoginRes from public import msg_client.proto
type ClientLoginRes msg_client.ClientLoginRes

func (m *ClientLoginRes) Reset()         { (*msg_client.ClientLoginRes)(m).Reset() }
func (m *ClientLoginRes) String() string { return (*msg_client.ClientLoginRes)(m).String() }
func (*ClientLoginRes) ProtoMessage()    {}
func (m *ClientLoginRes) GetUid() uint64 { return (*msg_client.ClientLoginRes)(m).GetUid() }

// ClientRegisterReq from public import msg_client.proto
type ClientRegisterReq msg_client.ClientRegisterReq

func (m *ClientRegisterReq) Reset()         { (*msg_client.ClientRegisterReq)(m).Reset() }
func (m *ClientRegisterReq) String() string { return (*msg_client.ClientRegisterReq)(m).String() }
func (*ClientRegisterReq) ProtoMessage()    {}
func (m *ClientRegisterReq) GetAccounts() string {
	return (*msg_client.ClientRegisterReq)(m).GetAccounts()
}
func (m *ClientRegisterReq) GetPassword() string {
	return (*msg_client.ClientRegisterReq)(m).GetPassword()
}
func (m *ClientRegisterReq) GetChannel() int32 { return (*msg_client.ClientRegisterReq)(m).GetChannel() }

// ClientRegisterRes from public import msg_client.proto
type ClientRegisterRes msg_client.ClientRegisterRes

func (m *ClientRegisterRes) Reset()         { (*msg_client.ClientRegisterRes)(m).Reset() }
func (m *ClientRegisterRes) String() string { return (*msg_client.ClientRegisterRes)(m).String() }
func (*ClientRegisterRes) ProtoMessage()    {}
func (m *ClientRegisterRes) GetUid() uint64 { return (*msg_client.ClientRegisterRes)(m).GetUid() }

// QueryRoleListReq from public import msg_client.proto
type QueryRoleListReq msg_client.QueryRoleListReq

func (m *QueryRoleListReq) Reset()         { (*msg_client.QueryRoleListReq)(m).Reset() }
func (m *QueryRoleListReq) String() string { return (*msg_client.QueryRoleListReq)(m).String() }
func (*QueryRoleListReq) ProtoMessage()    {}
func (m *QueryRoleListReq) GetUid() uint64 { return (*msg_client.QueryRoleListReq)(m).GetUid() }

// QueryRoleListRes from public import msg_client.proto
type QueryRoleListRes msg_client.QueryRoleListRes

func (m *QueryRoleListRes) Reset()         { (*msg_client.QueryRoleListRes)(m).Reset() }
func (m *QueryRoleListRes) String() string { return (*msg_client.QueryRoleListRes)(m).String() }
func (*QueryRoleListRes) ProtoMessage()    {}

// CreateRoleReq from public import msg_client.proto
type CreateRoleReq msg_client.CreateRoleReq

func (m *CreateRoleReq) Reset()          { (*msg_client.CreateRoleReq)(m).Reset() }
func (m *CreateRoleReq) String() string  { return (*msg_client.CreateRoleReq)(m).String() }
func (*CreateRoleReq) ProtoMessage()     {}
func (m *CreateRoleReq) GetUid() uint64  { return (*msg_client.CreateRoleReq)(m).GetUid() }
func (m *CreateRoleReq) GetName() string { return (*msg_client.CreateRoleReq)(m).GetName() }
func (m *CreateRoleReq) GetHead() string { return (*msg_client.CreateRoleReq)(m).GetHead() }

// CreateRoleRes from public import msg_client.proto
type CreateRoleRes msg_client.CreateRoleRes

func (m *CreateRoleRes) Reset()         { (*msg_client.CreateRoleRes)(m).Reset() }
func (m *CreateRoleRes) String() string { return (*msg_client.CreateRoleRes)(m).String() }
func (*CreateRoleRes) ProtoMessage()    {}

// 注册服务
type RegisterServiceRequest struct {
	ServerType uint32 `protobuf:"varint,1,opt,name=server_type,json=serverType" json:"server_type,omitempty"`
	RpcPort    string `protobuf:"bytes,2,opt,name=rpc_port,json=rpcPort" json:"rpc_port,omitempty"`
}

func (m *RegisterServiceRequest) Reset()                    { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()               {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterServiceRequest) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *RegisterServiceRequest) GetRpcPort() string {
	if m != nil {
		return m.RpcPort
	}
	return ""
}

type RegisterServiceResponse struct {
	ErrorCode error_code.EnumErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=error_code.EnumErrorCode" json:"error_code,omitempty"`
	ServerId  uint32                   `protobuf:"varint,2,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
}

func (m *RegisterServiceResponse) Reset()                    { *m = RegisterServiceResponse{} }
func (m *RegisterServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterServiceResponse) ProtoMessage()               {}
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterServiceResponse) GetErrorCode() error_code.EnumErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return error_code.EnumErrorCode_SUCCESS
}

func (m *RegisterServiceResponse) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

// 请求服务列表
type ServiceItem struct {
	ServerId   uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerType uint32 `protobuf:"varint,2,opt,name=server_type,json=serverType" json:"server_type,omitempty"`
	Ip         string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
}

func (m *ServiceItem) Reset()                    { *m = ServiceItem{} }
func (m *ServiceItem) String() string            { return proto.CompactTextString(m) }
func (*ServiceItem) ProtoMessage()               {}
func (*ServiceItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceItem) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ServiceItem) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ServiceItem) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServiceItem) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type QueryServiceListResponse struct {
	ErrorCode  error_code.EnumErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=error_code.EnumErrorCode" json:"error_code,omitempty"`
	ServerList []*ServiceItem           `protobuf:"bytes,2,rep,name=server_list,json=serverList" json:"server_list,omitempty"`
}

func (m *QueryServiceListResponse) Reset()                    { *m = QueryServiceListResponse{} }
func (m *QueryServiceListResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryServiceListResponse) ProtoMessage()               {}
func (*QueryServiceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryServiceListResponse) GetErrorCode() error_code.EnumErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return error_code.EnumErrorCode_SUCCESS
}

func (m *QueryServiceListResponse) GetServerList() []*ServiceItem {
	if m != nil {
		return m.ServerList
	}
	return nil
}

// 更新服务列表
type UpdateServiceListRequest struct {
	ServerList []*ServiceItem `protobuf:"bytes,1,rep,name=server_list,json=serverList" json:"server_list,omitempty"`
}

func (m *UpdateServiceListRequest) Reset()                    { *m = UpdateServiceListRequest{} }
func (m *UpdateServiceListRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateServiceListRequest) ProtoMessage()               {}
func (*UpdateServiceListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateServiceListRequest) GetServerList() []*ServiceItem {
	if m != nil {
		return m.ServerList
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterServiceRequest)(nil), "msg_server.RegisterServiceRequest")
	proto.RegisterType((*RegisterServiceResponse)(nil), "msg_server.RegisterServiceResponse")
	proto.RegisterType((*ServiceItem)(nil), "msg_server.ServiceItem")
	proto.RegisterType((*QueryServiceListResponse)(nil), "msg_server.QueryServiceListResponse")
	proto.RegisterType((*UpdateServiceListRequest)(nil), "msg_server.UpdateServiceListRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RpcService service

type RpcServiceClient interface {
	// 服务注册
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// 服务请求
	QueryServiceList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*QueryServiceListResponse, error)
	// 服务更新
	UpdateServiceList(ctx context.Context, in *UpdateServiceListRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// 用户注册
	ClientRegister(ctx context.Context, in *msg_client.ClientRegisterReq, opts ...grpc.CallOption) (*msg_client.ClientRegisterRes, error)
	// 用户登录
	ClientLogin(ctx context.Context, in *msg_client.ClientLoginReq, opts ...grpc.CallOption) (*msg_client.ClientLoginRes, error)
	// 获取角色列表
	QueryRoleList(ctx context.Context, in *msg_client.QueryRoleListReq, opts ...grpc.CallOption) (*msg_client.QueryRoleListRes, error)
	// 创建角色
	CreateRole(ctx context.Context, in *msg_client.CreateRoleReq, opts ...grpc.CallOption) (*msg_client.CreateRoleRes, error)
}

type rpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewRpcServiceClient(cc *grpc.ClientConn) RpcServiceClient {
	return &rpcServiceClient{cc}
}

func (c *rpcServiceClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	out := new(RegisterServiceResponse)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/RegisterService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) QueryServiceList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*QueryServiceListResponse, error) {
	out := new(QueryServiceListResponse)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/QueryServiceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) UpdateServiceList(ctx context.Context, in *UpdateServiceListRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/UpdateServiceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ClientRegister(ctx context.Context, in *msg_client.ClientRegisterReq, opts ...grpc.CallOption) (*msg_client.ClientRegisterRes, error) {
	out := new(msg_client.ClientRegisterRes)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/ClientRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ClientLogin(ctx context.Context, in *msg_client.ClientLoginReq, opts ...grpc.CallOption) (*msg_client.ClientLoginRes, error) {
	out := new(msg_client.ClientLoginRes)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/ClientLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) QueryRoleList(ctx context.Context, in *msg_client.QueryRoleListReq, opts ...grpc.CallOption) (*msg_client.QueryRoleListRes, error) {
	out := new(msg_client.QueryRoleListRes)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/QueryRoleList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) CreateRole(ctx context.Context, in *msg_client.CreateRoleReq, opts ...grpc.CallOption) (*msg_client.CreateRoleRes, error) {
	out := new(msg_client.CreateRoleRes)
	err := grpc.Invoke(ctx, "/msg_server.rpc_service/CreateRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RpcService service

type RpcServiceServer interface {
	// 服务注册
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// 服务请求
	QueryServiceList(context.Context, *google_protobuf.Empty) (*QueryServiceListResponse, error)
	// 服务更新
	UpdateServiceList(context.Context, *UpdateServiceListRequest) (*google_protobuf.Empty, error)
	// 用户注册
	ClientRegister(context.Context, *msg_client.ClientRegisterReq) (*msg_client.ClientRegisterRes, error)
	// 用户登录
	ClientLogin(context.Context, *msg_client.ClientLoginReq) (*msg_client.ClientLoginRes, error)
	// 获取角色列表
	QueryRoleList(context.Context, *msg_client.QueryRoleListReq) (*msg_client.QueryRoleListRes, error)
	// 创建角色
	CreateRole(context.Context, *msg_client.CreateRoleReq) (*msg_client.CreateRoleRes, error)
}

func RegisterRpcServiceServer(s *grpc.Server, srv RpcServiceServer) {
	s.RegisterService(&_RpcService_serviceDesc, srv)
}

func _RpcService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_QueryServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).QueryServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/QueryServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).QueryServiceList(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_UpdateServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).UpdateServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/UpdateServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).UpdateServiceList(ctx, req.(*UpdateServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_ClientRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(msg_client.ClientRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).ClientRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/ClientRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).ClientRegister(ctx, req.(*msg_client.ClientRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_ClientLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(msg_client.ClientLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).ClientLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/ClientLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).ClientLogin(ctx, req.(*msg_client.ClientLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_QueryRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(msg_client.QueryRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).QueryRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/QueryRoleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).QueryRoleList(ctx, req.(*msg_client.QueryRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(msg_client.CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg_server.rpc_service/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).CreateRole(ctx, req.(*msg_client.CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg_server.rpc_service",
	HandlerType: (*RpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _RpcService_RegisterService_Handler,
		},
		{
			MethodName: "QueryServiceList",
			Handler:    _RpcService_QueryServiceList_Handler,
		},
		{
			MethodName: "UpdateServiceList",
			Handler:    _RpcService_UpdateServiceList_Handler,
		},
		{
			MethodName: "ClientRegister",
			Handler:    _RpcService_ClientRegister_Handler,
		},
		{
			MethodName: "ClientLogin",
			Handler:    _RpcService_ClientLogin_Handler,
		},
		{
			MethodName: "QueryRoleList",
			Handler:    _RpcService_QueryRoleList_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _RpcService_CreateRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_server.proto",
}

func init() { proto.RegisterFile("msg_server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x08, 0x9a, 0xb1, 0x12, 0xc2, 0x1c, 0x5a, 0xd7, 0xa1, 0xa2, 0x32, 0x1c, 0x72,
	0x72, 0xa4, 0x70, 0x41, 0x1c, 0x1b, 0xf5, 0x50, 0x51, 0xa1, 0xd4, 0x84, 0x4b, 0x2f, 0x56, 0x6a,
	0x0f, 0x96, 0x25, 0x27, 0xbb, 0xdd, 0xdd, 0x14, 0xe5, 0x5f, 0xf0, 0x6b, 0xf8, 0x7d, 0x68, 0x77,
	0xf3, 0x61, 0x27, 0x38, 0xe2, 0xd0, 0xdb, 0xfa, 0xbd, 0xd9, 0x37, 0xf3, 0x66, 0x66, 0x0d, 0xbd,
	0xb9, 0xcc, 0x13, 0x49, 0xe2, 0x99, 0x44, 0xc4, 0x05, 0x53, 0x0c, 0x61, 0x87, 0x04, 0xfd, 0x9c,
	0xb1, 0xbc, 0xa4, 0xa1, 0x61, 0x1e, 0x97, 0x3f, 0x87, 0x34, 0xe7, 0x6a, 0x65, 0x03, 0x83, 0x1e,
	0x09, 0xc1, 0x44, 0x92, 0xb2, 0x8c, 0x36, 0x88, 0xbe, 0x9a, 0x96, 0x05, 0x2d, 0x94, 0x45, 0xc2,
	0x29, 0x9c, 0xc5, 0x94, 0x17, 0x52, 0x91, 0xf8, 0x4e, 0xe2, 0xb9, 0x48, 0x29, 0xa6, 0xa7, 0x25,
	0x49, 0x85, 0xef, 0xc1, 0xb3, 0x49, 0x12, 0xb5, 0xe2, 0xe4, 0x3b, 0x57, 0xce, 0xa0, 0x13, 0x83,
	0x85, 0xa6, 0x2b, 0x4e, 0x78, 0x01, 0xa7, 0x82, 0xa7, 0x09, 0x67, 0x42, 0xf9, 0xee, 0x95, 0x33,
	0x68, 0xc7, 0xaf, 0x05, 0x4f, 0x27, 0x4c, 0xa8, 0x50, 0xc0, 0xf9, 0x81, 0xaa, 0xe4, 0x6c, 0x21,
	0x09, 0xbf, 0x00, 0xec, 0xca, 0x32, 0xaa, 0xdd, 0x51, 0x3f, 0xaa, 0x54, 0x4a, 0x8b, 0xe5, 0x3c,
	0xd9, 0x7d, 0xc7, 0x6d, 0x73, 0x1e, 0xb3, 0x8c, 0xb0, 0x0f, 0xed, 0x75, 0x49, 0x45, 0x66, 0x52,
	0x76, 0xe2, 0x53, 0x0b, 0xdc, 0x66, 0x21, 0x03, 0x6f, 0x9d, 0xeb, 0x56, 0xd1, 0xbc, 0x1e, 0xeb,
	0xd4, 0x63, 0xf7, 0xbd, 0xb9, 0x07, 0xde, 0xba, 0xe0, 0x16, 0xdc, 0x3f, 0x31, 0xae, 0xdc, 0x82,
	0x23, 0x42, 0xcb, 0xf8, 0x6c, 0x19, 0xc4, 0x9c, 0xc3, 0xdf, 0x0e, 0xf8, 0xf7, 0x4b, 0x12, 0xab,
	0x75, 0xda, 0xbb, 0x42, 0xaa, 0x17, 0xb1, 0xf9, 0x79, 0x5b, 0x5d, 0x59, 0x48, 0xdd, 0xdb, 0x93,
	0x81, 0x37, 0x3a, 0x8f, 0x2a, 0x8b, 0x50, 0x31, 0xba, 0x29, 0x5b, 0x67, 0x0f, 0xa7, 0xe0, 0xff,
	0xe0, 0xd9, 0x4c, 0x51, 0xad, 0x24, 0x3b, 0xcf, 0x3d, 0x55, 0xe7, 0xbf, 0x55, 0x47, 0x7f, 0x5a,
	0xe0, 0xe9, 0x49, 0x4b, 0xcb, 0xe3, 0x03, 0xbc, 0xd9, 0x9b, 0x2e, 0x86, 0x55, 0x9d, 0x7f, 0x2f,
	0x54, 0xf0, 0xe1, 0x68, 0xcc, 0xba, 0x6f, 0x13, 0xe8, 0xed, 0xf7, 0x14, 0xcf, 0x22, 0xbb, 0xe5,
	0xd1, 0x66, 0xcb, 0xa3, 0x1b, 0xbd, 0xe5, 0xc1, 0xc7, 0xaa, 0x60, 0xe3, 0x24, 0xee, 0xe1, 0xed,
	0x41, 0x4f, 0xb0, 0x76, 0xb5, 0xa9, 0x65, 0x41, 0x43, 0x62, 0xfc, 0x06, 0xdd, 0xb1, 0x79, 0x44,
	0x1b, 0x17, 0x78, 0x19, 0x55, 0x5e, 0x56, 0x9d, 0x8b, 0xe9, 0x29, 0x38, 0x4a, 0x4b, 0xbc, 0x01,
	0xcf, 0x82, 0x77, 0x2c, 0x2f, 0x16, 0x18, 0x1c, 0x46, 0x1b, 0x42, 0x2b, 0x35, 0x73, 0x12, 0xbf,
	0x42, 0xc7, 0x74, 0x21, 0x66, 0xa5, 0x75, 0xf9, 0xae, 0x1a, 0x5c, 0xa3, 0xb4, 0xd4, 0x31, 0x56,
	0xe2, 0x35, 0xc0, 0x58, 0xd0, 0x4c, 0x91, 0x06, 0xf1, 0xa2, 0x96, 0x76, 0x8b, 0x6b, 0x99, 0x46,
	0x4a, 0x5e, 0x5f, 0x3e, 0xf4, 0x25, 0x9f, 0x09, 0xc1, 0x7e, 0xd9, 0x1f, 0x54, 0xca, 0xca, 0xe1,
	0xae, 0xef, 0x13, 0x67, 0xe2, 0x3e, 0xbe, 0x32, 0xc4, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x80, 0xdd, 0xa5, 0xe7, 0x04, 0x00, 0x00,
}
