// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error_msg.proto

/*
Package error_msg is a generated protocol buffer package.

It is generated from these files:
	error_msg.proto

It has these top-level messages:
*/
package error_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnumErrorCode int32

const (
	EnumErrorCode_SUCCESS EnumErrorCode = 0
	EnumErrorCode_FAILD   EnumErrorCode = 1
)

var EnumErrorCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILD",
}
var EnumErrorCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAILD":   1,
}

func (x EnumErrorCode) String() string {
	return proto.EnumName(EnumErrorCode_name, int32(x))
}
func (EnumErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("error_msg.EnumErrorCode", EnumErrorCode_name, EnumErrorCode_value)
}

func init() { proto.RegisterFile("error_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2d, 0x2a, 0xca,
	0x2f, 0x8a, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x68,
	0x69, 0x72, 0xf1, 0xa7, 0xe6, 0x95, 0xe6, 0xc6, 0x43, 0x44, 0x92, 0xf3, 0x53, 0x52, 0x85, 0xb8,
	0xb9, 0xd8, 0x83, 0x43, 0x9d, 0x9d, 0x5d, 0x83, 0x83, 0x05, 0x18, 0x84, 0x38, 0xb9, 0x58, 0xdd,
	0x1c, 0x3d, 0x7d, 0x5c, 0x04, 0x18, 0x9d, 0x78, 0xa3, 0xb8, 0xf5, 0xf4, 0xe1, 0x3a, 0x93, 0xd8,
	0xc0, 0x66, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x85, 0x09, 0x93, 0x5e, 0x00, 0x00,
	0x00,
}
