// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_code.proto

/*
Package msg_code is a generated protocol buffer package.

It is generated from these files:
	msg_code.proto

It has these top-level messages:
*/
package msg_code

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnumMsgCode int32

const (
	EnumMsgCode_DEFAULT             EnumMsgCode = 0
	EnumMsgCode_CS_CLIENT_LOGIN_REQ EnumMsgCode = 10001
	EnumMsgCode_SC_CLIENT_LOGIN_RES EnumMsgCode = 10002
)

var EnumMsgCode_name = map[int32]string{
	0:     "DEFAULT",
	10001: "CS_CLIENT_LOGIN_REQ",
	10002: "SC_CLIENT_LOGIN_RES",
}
var EnumMsgCode_value = map[string]int32{
	"DEFAULT":             0,
	"CS_CLIENT_LOGIN_REQ": 10001,
	"SC_CLIENT_LOGIN_RES": 10002,
}

func (x EnumMsgCode) String() string {
	return proto.EnumName(EnumMsgCode_name, int32(x))
}
func (EnumMsgCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("msg_code.EnumMsgCode", EnumMsgCode_name, EnumMsgCode_value)
}

func init() { proto.RegisterFile("msg_code.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2d, 0x4e, 0x8f,
	0x4f, 0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xb5, 0x02,
	0xb8, 0x78, 0x53, 0xf3, 0x4a, 0x73, 0xe3, 0x61, 0x02, 0x42, 0xdc, 0x5c, 0xec, 0x2e, 0xae, 0x6e,
	0x8e, 0xa1, 0x3e, 0x21, 0x02, 0x0c, 0x42, 0x12, 0x5c, 0xc2, 0xce, 0xc1, 0xf1, 0xce, 0x3e, 0x9e,
	0xae, 0x7e, 0x21, 0xf1, 0x3e, 0xfe, 0xee, 0x9e, 0x7e, 0xf1, 0x41, 0xae, 0x81, 0x02, 0x13, 0xfd,
	0x40, 0x32, 0xc1, 0xce, 0xe8, 0x32, 0xc1, 0x02, 0x93, 0xfc, 0x9c, 0x78, 0xa2, 0xb8, 0xf4, 0xf4,
	0x61, 0xc6, 0x25, 0xb1, 0x81, 0x2d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x84, 0x31, 0xd1,
	0x01, 0x82, 0x00, 0x00, 0x00,
}
