// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_test.proto

/*
Package msg_test is a generated protocol buffer package.

It is generated from these files:
	msg_test.proto

It has these top-level messages:
	Role
*/
package msg_test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 角色信息
type Role struct {
	RoleId   uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	Head     string `protobuf:"bytes,3,opt,name=head" json:"head,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Role) GetRoleId() uint64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Role) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Role) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func init() {
	proto.RegisterType((*Role)(nil), "msg_test.Role")
}

func init() { proto.RegisterFile("msg_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2d, 0x4e, 0x8f,
	0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x02,
	0xb8, 0x58, 0x82, 0xf2, 0x73, 0x52, 0x85, 0xc4, 0xb9, 0xd8, 0x8b, 0xf2, 0x73, 0x52, 0xe3, 0x33,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x69, 0x2e,
	0x4e, 0xb0, 0x44, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x07, 0x48,
	0xc0, 0x2f, 0x31, 0x37, 0x55, 0x48, 0x88, 0x8b, 0x25, 0x23, 0x35, 0x31, 0x45, 0x82, 0x19, 0x2c,
	0x0e, 0x66, 0x3b, 0xf1, 0x44, 0x71, 0xe9, 0xe9, 0xc3, 0xcc, 0x4f, 0x62, 0x03, 0x5b, 0x68, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x87, 0x0d, 0x3c, 0x82, 0x00, 0x00, 0x00,
}
