
CREATE DATABASE IF NOT EXISTS db_global
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_center_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_dispatch_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_login_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_logic_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_item_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_chat_server
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS db_log
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;